### ISSUE TITLE
App在前台时, 手机在长时间关闭屏幕, 再回到页面时, 页面显示尺寸异常

### ISSUE THREAD

**Issue by a342216937** [feisher/ScreenAdapter#4]
App在前台时, 手机在长时间关闭屏幕, 再回到页面时, 页面显示尺寸异常

各位有什么解决办法吗

**Comment by feisher** [comment]
可以试试新增的AdaptScreenUtils.java，同样是一个工具类，用法接近，不过适配时机不再使用ActivityLifecycleCallbacks，，而是改由重写BaseActivity
override fun getResources(): Resources {
       return AdaptScreenUtils.adaptWidth(super.getResources(), 1280)
}

**Comment by feisher** [comment]
@a342216937

**Comment by a342216937** [comment]
多谢 我试了试 应该是没问题了
